# Generated by Django 4.1 on 2023-11-29 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Власники',
                'verbose_name_plural': 'Власники',
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Імя')),
                ('limit', models.IntegerField(verbose_name='Обмеження')),
            ],
            options={
                'verbose_name': 'Обмеження інстаграма',
                'verbose_name_plural': 'Обмеження інстаграма',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Шаблон відповіді')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблони',
            },
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, validators=[django.core.validators.MaxValueValidator(255)], verbose_name='Логін')),
                ('password', models.BinaryField(verbose_name='Пароль')),
                ('password_key', models.BinaryField(blank=True, null=True, verbose_name='Ключ для пароля')),
                ('age', models.CharField(choices=[('FIRST', '0 - 21'), ('SECOND', '21 - 90'), ('THIRD', '90 - 180'), ('LAST', '180+')], default='FIRST', max_length=6, verbose_name='Вік профілю (дні)')),
                ('message', models.IntegerField(default=0, verbose_name='Кількість повідомлень - надіслані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Користувач Інстаграма',
                'verbose_name_plural': 'Користувачі інтаграма',
            },
        ),
    ]
