# Generated by Django 4.1 on 2023-11-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Імя')),
                ('limit', models.IntegerField(verbose_name='Обмеження')),
            ],
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='login',
            field=models.BinaryField(editable=True, verbose_name='Логін'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.BinaryField(editable=True, verbose_name='Пароль'),
        ),
    ]
