# Generated by Django 4.1 on 2023-12-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='message',
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Силка на сторінку')),
                ('page_id', models.CharField(max_length=255, verbose_name='Отримувач')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Список користувачів',
                'verbose_name_plural': 'Список користувачів',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.BooleanField(default=False, verbose_name='Конкурент')),
                ('recipient', models.CharField(max_length=255, verbose_name='Отримувач')),
                ('direct_message', models.TextField(verbose_name='Текст повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Дані розсилки',
                'verbose_name_plural': 'Дані розсилки',
            },
        ),
        migrations.CreateModel(
            name='ListName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва списку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач')),
                ('user_list', models.ManyToManyField(to='app.userid', verbose_name='Список користувачів')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
    ]
