# Generated by Django 4.1 on 2023-11-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_limit_alter_instagramuser_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='limit',
            options={'verbose_name': 'Обмеження інстаграма', 'verbose_name_plural': 'Обмеження інстаграма'},
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='login_key',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='follower',
            field=models.IntegerField(default=0, verbose_name='Читачі'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Головна сторінка'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Імя'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Вартість просування'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='target',
            field=models.IntegerField(default=0, verbose_name='Ціль підписників'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='track',
            field=models.IntegerField(default=0, verbose_name='Підписники'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='login',
            field=models.CharField(max_length=255, verbose_name='Логін'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.BinaryField(verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='teg',
            field=models.ManyToManyField(to='app.teg', verbose_name='Теги'),
        ),
    ]
