# Generated by Django 4.1 on 2023-11-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teg_alter_limit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='sum',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='system',
            field=models.BooleanField(default=False, verbose_name='Системна сторінка'),
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Номер сторінки в інстаграмі')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teg', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Індифікатор користувачів по тегу',
                'verbose_name_plural': 'Індифікатори користувачів по тегу',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість просування')),
                ('currency', models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар'), ('EUR', 'Євро')], default='UAH', max_length=3, verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instagramuser', verbose_name='Інстаграм сторінка')),
            ],
            options={
                'verbose_name': 'Дохід',
                'verbose_name_plural': 'Доходи',
            },
        ),
    ]
