# Generated by Django 4.1.8 on 2023-12-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_limit_description_systemsetting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instagramuser', verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, verbose_name='Номер сторінки')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Послідовувач',
                'verbose_name_plural': 'Послідовувачі',
            },
        ),
    ]
