# Generated by Django 4.1 on 2023-11-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_template_income_created_at_income_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
            },
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активувати'),
        ),
        migrations.AddConstraint(
            model_name='userid',
            constraint=models.UniqueConstraint(fields=('user_id', 'teg'), name='unique_user_teg'),
        ),
    ]
