# Generated by Django 4.1.8 on 2023-12-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userid_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='created_at',
        ),
    ]
