# Generated by Django 4.1 on 2023-11-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_systemsetting_instagramuser_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='password_key',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='uniq_following',
            field=models.BooleanField(default=False, verbose_name='Унікальність підписок'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
