# Generated by Django 4.1.8 on 2023-12-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_followers_account_alter_instagramuser_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
