# Generated by Django 4.1.8 on 2023-12-13 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramuser',
            options={'verbose_name': 'Акаунт', 'verbose_name_plural': 'Акаунти'},
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='password_secure',
            field=models.BinaryField(blank=True, null=True, verbose_name='Засекречений пароль'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='system',
            field=models.BooleanField(default=False, verbose_name='Системний акаунт'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.CharField(default='****', max_length=255, validators=[django.core.validators.MaxValueValidator(255)], verbose_name='Пароль'),
        ),
    ]
