# Generated by Django 4.1.8 on 2023-12-13 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_instagramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='page_id',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(limit_value=255)], verbose_name='Номер сторінки'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='login',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(limit_value=255)], verbose_name='Логін'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='password',
            field=models.CharField(default='****', max_length=255, validators=[django.core.validators.MaxLengthValidator(limit_value=255)], verbose_name='Пароль'),
        ),
    ]
