# Generated by Django 4.1.8 on 2023-12-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_template_description_template_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instagramuser', verbose_name='Акаунт'),
        ),
    ]
