# Generated by Django 4.1.8 on 2023-12-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_template_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageByUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Лінк на сторінку')),
                ('direct_message', models.TextField(verbose_name='Текст повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('accounts', models.ManyToManyField(to='app.instagramuser', verbose_name='Аккаунти')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Розсилка по аккаунту',
                'verbose_name_plural': 'Розсилки по аккаунту',
            },
        ),
        migrations.CreateModel(
            name='SendMessageByList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_message', models.TextField(verbose_name='Текст повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('accounts', models.ManyToManyField(to='app.instagramuser', verbose_name='Аккаунти')),
                ('lists', models.ManyToManyField(to='app.listname', verbose_name='Списки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Розсилка по списку',
                'verbose_name_plural': 'Розсилки по списку',
            },
        ),
    ]
