# Generated by Django 4.1.8 on 2024-01-10 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_alter_listname_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('page_id', 'account')},
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Текст повідомлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Шаблон повідомлень',
                'verbose_name_plural': 'Шаблони повідомлень',
            },
        ),
        migrations.AlterField(
            model_name='sendmessagebylist',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.messagetemplate', verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='sendmessagebyurl',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.messagetemplate', verbose_name='Текст повідомлення'),
        ),
    ]
