# Generated by Django 4.1.8 on 2024-02-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_alter_followers_unique_together_messagetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Список для шаблонів',
                'verbose_name_plural': 'Списки для шаблонів',
            },
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namemessagetemplate', verbose_name='Список'),
        ),
        migrations.AlterField(
            model_name='sendmessagebylist',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namemessagetemplate', verbose_name='Список повідомлень'),
        ),
        migrations.AlterField(
            model_name='sendmessagebyurl',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namemessagetemplate', verbose_name='Список повідомлень'),
        ),
    ]
