# Generated by Django 4.1.8 on 2024-02-09 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_namemessagetemplate_alter_messagetemplate_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='namemessagetemplate',
            unique_together={('name', 'user')},
        ),
    ]
