# Generated by Django 4.1.8 on 2024-03-06 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_alter_namemessagetemplate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='system',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний акаунт'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(choices=[('URL', 'url'), ('LIST', 'list'), ('DIRECT', 'direct')], default='DIRECT', max_length=6, verbose_name='Тип завдання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complited', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instagramuser', verbose_name='Аккаунт')),
                ('direct_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namemessagetemplate', verbose_name='Список повідомлень')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.listname', verbose_name='Список користувачів')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.CreateModel(
            name='AccountCounterTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveSmallIntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.instagramuser')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лічильник для завдання',
                'verbose_name_plural': 'Лічильник для завдань',
                'unique_together': {('account', 'user')},
            },
        ),
    ]
